#!/usr/bin/env bash
vol=$(pamixer --get-volume)

if $(pamixer --get-mute); then
	echo "ﱝ"
else
	if (($vol > 90)); then
		echo $vol
	elif (($vol > 75)); then
		echo 墳$vol
	elif (($vol > 50)); then
		echo 奔$vol
	elif (($vol > 25)); then
		echo 奔$vol
	elif (($vol < 25)); then
		echo $vol
	fi
fi

